version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    restart: always
    networks:
      - devnet

  mongo:
    image: mongo:4.4
    volumes:
      - mongodata:/data/db
    networks:
      - devnet

volumes:
  mongodata:

networks:
  devnet:
    driver: bridge